urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.template import add_to_builtins

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^robots.txt$', 'django.views.generic.simple.direct_to_template', {
                'template': 'robots.txt' }),
    (r'^admin/', include(admin.site.urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^users/', include('users.urls')),
    (r'^questions/', include('quest.urls')),
    (r'^tasks/', include('tasks.urls')),
    (r'^utils/', include('utils.urls')),
)

urlpatterns += patterns('users.views',
    (r'^$', 'view_homepage', {'homepage_template':'homepage.html'}, 'homepage'),
    (r'^dashboard/$', 'view_dashboard', {'dashboard_template':'dashboard.html'}, 'dashboard'),
    (r'^notepad/$', 'view_notepad', {'notepad_template':'notepad.html'}, 'notepad'),
    (r'^webresume/$', 'view_webresume', {}, 'webresume'),
    (r'^invite/$', 'view_invite', {'invite_template':'invite.html'}, 'invite'),
    (r'^achievements/$', 'view_all_achievements', {'achievements_template':'achievements.html'}, 'achievements'),
)

urlpatterns += patterns('users.views',
    (r'^accounts/register/$', 'view_register', {'registration_template': 'register.html'}, 'register'),
    (r'^accounts/studentregister/$', 'view_register', {'registration_template': 'student_register.html', 'user_type':'S'}, 'student_register'),
    (r'^accounts/employeeregister/$', 'view_register', {'registration_template': 'employee_register.html', 'user_type':'E'}, 'employee_register'),
    (r'^accounts/professorregister/$', 'view_register', {'registration_template': 'professor_register.html', 'user_type':'P'}, 'professor_register'),
    (r'^accounts/login/$', 'view_login', {'login_template': 'login.html'}, 'login'),
    (r'^accounts/logout/$', 'view_logout', {'logout_template': 'logout.html'}, 'logout'),
    (r'^contactuser/(?P<user_id>\d+)/$', 'view_contactuser', {'contactuser_template':'contactuser.html'}, 'contactuser'),
    (r'^contactgroup/(?P<group_type>\w+)/(?P<group_id>\d+)/$', 'view_contactgroup', {'contactgroup_template':'contactgroup.html'}, 'contactgroup'),
    (r'^contactus/$', 'view_contactus', {'contactus_template':'contactus.html'}, 'contactus'),
    (r'^forgot_password/$', 'view_forgot_password', {'forgot_password_template':'forgot_password.html'}, 'forgot_password'),
    (r'^reset_my_password/$', 'view_reset_my_password', {'reset_my_password_template':'reset_my_password.html'}, 'reset_my_password'),
    (r'^add_achievement/$', 'view_add_achievement', {'add_achievement_template':'add_or_edit_achievement.html'}, 'add_achievement'),
    (r'^edit_achievement/(?P<achievement_id>\d+)/$', 'view_edit_achievement', {'edit_achievement_template':'add_or_edit_achievement.html'}, 'edit_achievement'),
)

urlpatterns += patterns('users.views',
    (r'^settings/$', 'view_account_settings', {'settings_template':'settings.html'}, 'settings'),
    (r'^settings/personal/$', 'view_save_personal_settings', {'personal_settings_template':'personal_settings.html'}, 'personal_settings'),
    (r'^settings/acad/$', 'view_save_acad_settings', {'acad_settings_template':'acad_settings.html'}, 'acad_settings'),
    (r'^settings/workinfo/$', 'view_save_workinfo_settings', {'workinfo_settings_template':'workinfo_settings.html'}, 'workinfo_settings'),                    
)

urlpatterns += patterns('users.views',
    (r'^colleges/$', 'view_colleges', {'colleges_template':'colleges.html'}, 'colleges'),
    (r'^colleges/(?P<college_id>\d+)/(?P<college_slug>[\w\s-]+)/$', 'view_college', {'college_template':'college.html'}, 'college_profile'),
)

urlpatterns += patterns('users.views',
    (r'^companies/$', 'view_all_companies', {'companies_template':'companies.html'}, 'companies'),
    (r'^companies/(?P<company_id>\d+)/(?P<company_slug>[\w\s-]+)/$', 'view_company', {'company_template':'company.html'}, 'company_profile'),
)

add_to_builtins('utils.templateutils')

users/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('users.views',
    (r'^$', 'view_all_users', {'all_users_template':'all_users.html'}, 'all_users'),
    (r'^(?P<user_slug_name>[\w\s-]+)/$', 'view_userprofile', {'userprofile_template':'user_profile.html'}, 'user_profile'),
    (r'^notes/(?P<note_id>\d+)/$', 'view_note', {}, 'show_note'),
    (r'^notes/(?P<note_id>\d+)/edit/$', 'view_edit_note', {'notepad_template':'notepad.html'}, 'edit_note'),
)

users/models.py
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from utils import slugify
from utils.models import BaseModel, BaseModelManager, YearField
import hashlib
from django.db.models.signals import post_save
from taggit.models import Tag

branches = (
    ('BCA', 'BCA'),
    ('BME', 'Bio-Medical'),
    ('BSc', 'BSc'),
    ('BTE', 'Bio-Tech'),
    ('CCE', 'Ceramics & Cement'),
    ('CHE', 'Chemical'),
    ('CSE', 'Computers'),
    ('CVE', 'Civil'),
    ('ECE', 'Electronics & Communications'),
    ('EEE', 'Electrical & Electronics'),
    ('ENVE', 'Environmental'),
    ('IE', 'Instrumentation'),
    ('MBA', 'MBA'),
    ('MCA', 'MCA'),
    ('ME', 'Mechanical'),
    ('MNE', 'Mining'),
    ('MSc', 'MSc'),
    ('MTech', 'MTech'),
    ('PGDBM', 'PGDBM'),
    ('PGDCA', 'PGDCA'),
    ('PTE', 'Printing'),
    ('PYE', 'Polymer'),
    ('TXE', 'Textile'),
)

SLUG_UPDATE_TIME_THRESHOLD_IN_SECONDS = 2

class UserProfileAlreadyExistsException(Exception):
    pass

class CantUpdateSlugAgainException(Exception):
    pass

class UserProfileManager(BaseModelManager):
    def create_profile(self, email, password, name):
        if self.exists(user__email=email):
            raise UserProfileAlreadyExistsException
        user = User.objects.create_user(username=self._compute_username(email),
                                        email=email,
                                        password=password)
        userprofile = UserProfile(user=user, name=name)
        userprofile.save()
        userprofile.award_score(settings.SEED_SCORE)
        return userprofile
    
    def _compute_username(self, email):
        return hashlib.sha1(email).hexdigest()[:30]
    
class UserProfile(BaseModel):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=50, db_index=True, null=True, blank=True)#this will be used as his unique url identifier
    objects = UserProfileManager()
    
    def __unicode__(self):
        return self.name

    def assign_task(self, task):
        from tasks.models import TaskMembership
        TaskMembership.objects.assign_task(task, self)

    def finish_task(self, task):
        task_assignments = task.taskmembership_set.filter(userprofile=self)
        if task_assignments.count():
            task_membership = task_assignments[0]
            task_membership.status = 'FINISHED'
            task_membership.save()
            self.award_score(task.bounty)
            return
        raise Exception, "Given task is not assigned to %s" % self

    @property
    def asked_questions(self):
        return self.question_set.values('title', 'id', 'slug')
    
    @property
    def answered_questions(self):
        #FIXME:the below import globally is causing circular import error
        from quest.models import Question
        #FIXME:the below query will bomb if the IN operator receives a million answer ids
        answers_ids = set([question['question_id'] for question in self.answer_set.values('question_id')])
        return Question.objects.filter(id__in=answers_ids).values('title', 'id', 'slug')
    
    @property
    def group_name(self):
        user_groups = self.user.groups
        if user_groups.count():
            return self.user.groups.all()[0].name
        return ''
    
    def make_student(self):
        user_groups = self.user.groups
        for group in user_groups.all():
            user_groups.remove(group)
        user_groups.add(Group.objects.get(name='Student'))
        
    def make_employee(self):
        user_groups = self.user.groups
        for group in user_groups.all():
            user_groups.remove(group)
        user_groups.add(Group.objects.get(name='Employee'))
        
    def make_professor(self):
        user_groups = self.user.groups
        for group in user_groups.all():
            user_groups.remove(group)
        user_groups.add(Group.objects.get(name='Professor'))
    
    @property    
    def is_student(self):
        return Group.objects.get(name="Student") in self.user.groups.all() 
        
    @property
    def is_professor(self):
        return Group.objects.get(name="Professor") in self.user.groups.all()
        
    @property
    def is_employee(self):
        return Group.objects.get(name="Employee") in self.user.groups.all()
    
    def join_college(self, college_name, branch='', start_year=None, end_year=None, aggregate=None):
        if college_name:
            AcadInfo.objects.filter(userprofile=self).delete()
            college_slug = slugify(college_name)
            if College.objects.exists(slug=college_slug):
                college = College.objects.get(slug=college_slug)
            else:
                college = College.objects.create_college(name=college_name)
            AcadInfo.objects.create_acadinfo(self, branch=branch, college=college, start_year=start_year, end_year=end_year, aggregate=aggregate)
        
    def join_workplace(self, workplace_name, workplace_type, designation='', years_of_exp=''):
        workplace_slug = slugify(workplace_name)
        if workplace_type and (self.is_employee or self.is_professor):
            if workplace_type == 'Company':
                if Company.objects.exists(slug=workplace_slug):
                    workplace = Company.objects.get(slug=workplace_slug)
                else:
                    workplace = Company.objects.create_company(name=workplace_name)
            elif workplace_type == 'College':
                if College.objects.exists(slug=workplace_slug):
                    workplace = College.objects.get(slug=workplace_slug)
                else:
                    workplace = College.objects.create_college(name=workplace_name)
            WorkInfo.objects.filter(userprofile=self).delete()
            WorkInfo.objects.create_workinfo(self, workplace=workplace, designation=designation, years_of_exp=years_of_exp)
        else:
            raise Exception, 'Student cant join a Workplace. He needs to be an Employee'
        
    @property
    def acad_details(self):
        acad_details = self.acadinfo_set
        if acad_details.count():
            acad_details = acad_details.values('branch', 'college', 'start_year', 'end_year', 'aggregate')[0]
            return (acad_details['branch'], College.objects.get(id=acad_details['college']), acad_details['start_year'], acad_details['end_year'], acad_details['aggregate'])
        return ('', None, '', '', '')
        
    @property
    def work_details(self):
        work_details = self.workinfo_set
        if work_details.count():
            work_details = work_details.values('content_type', 'object_id', 'designation', 'years_of_exp')[0]
            content_type = ContentType.objects.get(id=work_details['content_type'])
            return (content_type.get_object_for_this_type(id=work_details['object_id']), work_details['designation'], work_details['years_of_exp'] if work_details['years_of_exp'] else '')
        return (None, '', '')
    
#    @property
#    def interested_tags(self):
#        #NOTE:For now, all Q&A tags related to this user are pulled up. 
#        all_qa_tags = []
#        all_raised_questions = self.question_set.select_related()
#        for question in all_raised_questions:
#            all_qa_tags.extend([tag['name'] for tag in question.tags.values('name')])
#        all_given_answers = self.answer_set.all()
#        for answer in all_given_answers:
#            question_tags = [tag['name'] for tag in answer.question.tags.values('name')]
#            all_qa_tags.extend(question_tags)
#        return tuple(set(all_qa_tags))

    @property
    def interested_tags(self):
        from quest.models import Question
        #NOTE:For now, all Q&A tags related to this user are pulled up. 
        all_questions_tags = Tag.objects.filter(id__in=set([tag_info['tags'] for tag_info in self.question_set.select_related().values('tags')])).values('name')
        all_answers_tags = Tag.objects.filter(id__in=set([tag_info['tags'] for tag_info in Question.objects.filter(id__in=set([question_info['question'] for question_info in self.answer_set.select_related().values('question')])).values('tags')])).values('name')
        return tuple(set([tag_info['name'] for tag_info in all_questions_tags] + [tag_info['name'] for tag_info in all_answers_tags]))
    
    @property
    def helped_persons(self):
        persons = {}
        all_given_answers = self.answer_set.select_related()
        for answer in all_given_answers:
            person = answer.question.raised_by
            if (person.id != self.id) and (not persons.has_key(person.id)):
                persons[person.id] = (person.id, person.slug, person.name)
        return tuple(persons.values())
        
    def update(self, **kwargs):
        if 'password' in kwargs.keys():
            self.update_password(kwargs['password'])
            kwargs.pop('password')
        if 'slug' in kwargs.keys() and self.can_update_slug():
            self.update_slug(kwargs['slug'])
            kwargs.pop('slug')
        for key in kwargs:
            setattr(self, key, kwargs[key])
        self.save()
    
    def can_update_slug(self):
        if self.slug:
            return False
        return True

    @property
    def is_domain_enabled(self):
        if self.can_update_slug():
            return False
        return True
    
    def update_slug(self, new_slug_name):
        '''Ensuring slug cant be updated more than once'''
        if self.can_update_slug():
            self.slug = new_slug_name
            self.save()
            return
        raise CantUpdateSlugAgainException

    def check_password(self, password):
        return self.user.check_password(password)

users/templates/acad_settings.html
<h3 class='georgia leftalign'>Academic Settings</h3>
<form name="acad_settings_form" autocomplete="off">{% csrf_token %}
<table class='form-table'>
	<tr><td class='rightalign'><label for="id_college">College :</label></td><td class='leftalign'>{{acad_form.college}}&nbsp;(<span class='required'>Required</span>. Max of <span class='black_stress'>100</span> characters)</span><br/>{{acad_form.college.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_branch">Branch :</label></td><td class='leftalign'>{{acad_form.branch}}<br/>{{acad_form.branch.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_start_year">Start Year :</label></td><td class='leftalign'>{{acad_form.start_year}}<br/>{{acad_form.start_year.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_end_year">End Year :</label></td><td class='leftalign'>{{acad_form.end_year}}<br/>{{acad_form.end_year.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_end_year">Aggregate Score :</label></td><td class='leftalign'>{{acad_form.aggregate}}<br/>{{acad_form.aggregate.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input type='button' class='btn primary' id="save_acad_settings_button" name='save_acad_settings_button' value="Save my Academic Settings" onClick="javascript:save_acad_settings(this.form.name);"/></td></tr>
</table>
</form>

users/templates/college.html
{%extends 'base.html'%}
{% block title %}{{college.name|title}}{% endblock %}
{%block content%}
{%with college.name as college_name%}
<h2 class='georgia maincontent_header'>{{college_name|title}}</h2>
{%if students%}
<h3 class='georgia maincontent_header'><a id='contactgroup' href="{%url contactgroup 'college' college.id%}">Contact All {{college_name|title}} Students</a></h3>
{%load users_tags%}
<ul id='colleges_list' class='prepend-1'>
{%for student in students%}
<li>{%render_user_domain student %}</li>
{%empty%}
No Students Yet!
{%endfor%}
</ul>
{%endif%}
{%endwith%}
</ul>
{%endblock%}

users/templates/colleges.html
{%extends 'base.html'%}
{% block title %}All Colleges{% endblock %}
{%block content%}
<h2 class='georgia maincontent_header'>All Colleges</h2>
<ul id='colleges'>
{%for college in colleges%}
<li><h3><a href="{%url college_profile college.id college.slug%}">{{college.name|title}}</a></h3></li>
{%empty%}
No Colleges Yet!
{%endfor%}
</ul>
{%endblock%}

users/templates/company.html
{%extends 'base.html'%}
{% block title %}{{company.name|title}}{% endblock %}
{%block content%}
<h2 class='georgia maincontent_header'>{{company.name|title}} Employees</h2>
{%load users_tags%}
<ul id='companies'>
{%for employee in employees%}
<li><h3>{%render_user_domain employee %}</h3></li>
{%empty%}
No Employees Yet!
{%endfor%}
</ul>
{%endblock%}

users/templates/contactgroup.html
{%extends 'base.html'%}
{% block title %}Contact {{group_name|title}}{% endblock %}
{%block content%}
<h2 class='georgia maincontent_header blue_underline'>Contact {{group_name|title}}</h2>
<form action="{%url contactgroup group_type group_id%}" method='POST'>{% csrf_token %}
<table class='form-table'>
    <tr><td class='rightalign'><label for="id_to">To :</label></td><td class='leftalign'>{{contactgroupform.to}}</td></tr>
    <tr><td class='rightalign'><label for="id_subject">Subject :</label></td><td class='leftalign'>{{contactgroupform.subject}}<span class='help_text'>(<span class='optional'>Optional</span>. Max of 100 characters)</span><br/>{{contactgroupform.subject.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_message">Message :</label></td><td class='form-row'>{{contactgroupform.message}}<span class='help_text'>(<span class='required'>Required</span>. Max of 500 characters)</span>&nbsp;&nbsp;<span id='status_meter_id' class='small_text'></span><br/>{{contactgroupform.message.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input class='btn primary' type='submit' value='Send Message'/></td></tr>
</table>
</form>
{%endblock%}
{%block extrajs%}
<script type="text/javascript">
$('#id_message').keyup(function(e){
    charCounter({{contactgroupform.fields.message.max_length}}, 'id_message', 'status_meter_id');
});
</script>
{%endblock%}

users/templates/contactuser.html
{%extends 'base.html'%}
{% block title %}Contact {{to_userprofile.name|title}}{% endblock %}
{%block content%}
<h2 class='georgia maincontent_header blue_underline'>Contact {{to_userprofile.name|title}}</h2>
<form action="{%url contactuser to_userprofile.id%}" method='POST'>{% csrf_token %}
<table class='form-table'>
    <tr><td class='rightalign'><label for="id_to">To :</label></td><td class='leftalign'>{{contactuserform.to}}</td></tr>
    <tr><td class='rightalign'><label for="id_subject">Subject :</label></td><td class='leftalign'>{{contactuserform.subject}}<span class='help_text'>(<span class='optional'>Optional</span>. Max of 100 characters)</span><br/>{{contactuserform.subject.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_message">Message :</label></td><td class='form-row'>{{contactuserform.message}}<span class='help_text'>(<span class='required'>Required</span>. Max of 500 characters)</span>&nbsp;&nbsp;<span id='status_meter_id' class='small_text'></span><br/>{{contactuserform.message.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input class='btn primary' type='submit' value='Send Message'/></td></tr>
</table>
</form>
{%endblock%}
{%block extrajs%}
<script type="text/javascript">
$('#id_message').keyup(function(e){
    charCounter({{contactuserform.fields.message.max_length}}, 'id_message', 'status_meter_id');
});
</script>
{%endblock%}

users/templates/domain_url.html
{{domain_or_name|safe}}

users/templates/personal_settings.html
<h3 class='georgia leftalign'>Personal Settings</h3>
<form name="personal_settings_form" autocomplete="off">{% csrf_token %}
<table class='form-table'>
    <tr><td class='rightalign'><label for="id_name">Name :</label></td><td class='leftalign'>{{personal_form.name}}&nbsp;(<span class='required'>Required</span>. Max of <span class='black_stress'>50</span> characters)</span><br/>{{personal_form.name.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_slug">Web Resume Url :</label></td>
        <td class='leftalign'>
        {%if userprofile.can_update_slug%}
            {{personal_form.slug}}.{{site.domain}}<span class='help_text'>(This will be the url of your Public Resume page. Can't be changed, once picked)</span>
            <br/>{%autoescape off%}{{personal_form.slug.errors}}{%endautoescape%}
        {%else%}
            <a class='domain bold' target='_blank' href='{{userprofile.domain|domainify}}'>{{userprofile.domain|domainify}}</a>
        {%endif%}
        </td></tr>
    <tr><td class='rightalign'><label for="id_new_password">New Password :</label></td><td class='leftalign'>{{personal_form.new_password}}<span class='help_text'>(Leave this blank, if you dont wish to change the existing password)</span><br/>{{personal_form.new_password.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input type='button' class='btn primary' name="save_personal_settings_button" id="personal_settings_button" value="Save my Personal Settings" onClick="javascript:save_personal_settings(this.form.getAttribute('name'));"/></td></tr>
</table>
</form>

users/templates/professor_register.html
{%extends 'base.html'%}
{% block title %}Create a Professor Account{% endblock %}
{%block content%}
<div class='prepend-6 prepend-top'>
    <h3 class='registration_or_login_header prepend-2 georgia'>Already have an Account ? <a href="{%url login%}">Please Login</a></h3>
    <form action="{%url professor_register%}" method='POST' autocomplete="off">{% csrf_token %}
	<input type='hidden' name='next' value="{{next}}"/>
	<table class='form-table'>
	    <tr><td class='rightalign'><label for="id_email">Email :</label></td><td class='leftalign'>{{form.email}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.email.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_password">Password :</label></td><td class='leftalign'>{{form.password}}<span class='help_text'>(<span class='required'>Required</span>. Min of 6 characters. Max of 50 characters)</span><br/>{{form.password.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_name">Name :</label></td><td class='leftalign'>{{form.name}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.name.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_name">College :</label></td><td class='leftalign'>{{form.college}}<span class='help_text'>(<span class='required'>Required</span>. Max of 100 characters)</span><br/>{{form.college.errors}}</td></tr>
	    <tr><td>&nbsp;</td><td><input class='btn primary' type='submit' name='submit' value="Create my Account"/></td></tr>
	</table>
	</form>
</div>
{%endblock%}
{%block extrajs%}
<script type='text/javascript'>document.forms[0].email.focus();</script>
<script type='text/javascript' src="/site_media/js/jquery-ui/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type='text/javascript'>
$(document).ready(function(){
    var array = new Array();
    $('#id_college').autocomplete({
        dataType:'json',
        source:'{%url ajax_colleges_list%}',
        minLength:1,
    });
});
</script>
{%endblock%}
{%block extrastyle%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/js/jquery-ui/css/flick/jquery-ui-1.8.10.custom.css" />
{%endblock%}

users/templates/render_student_registerform.html
<form action="{%url student_register%}" method='POST' autocomplete="off">{% csrf_token %}
<input type='hidden' name='next' value="{{next}}"/>
<table class='form-table'>
    <tr><td class='rightalign'><label for="id_email">Email :</label></td><td class='leftalign'>{{form.email}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.email.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_password">Password :</label></td><td class='leftalign'>{{form.password}}<span class='help_text'>(<span class='required'>Required</span>. Min of 6 characters. Max of 50 characters)</span><br/>{{form.password.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_name">Name :</label></td><td class='leftalign'>{{form.name}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.name.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_college">College :</label></td><td class='leftalign'>{{form.college}}<span class='help_text'>(<span class='required'>Required</span>. Max of 100 characters)</span><br/>{{form.college.errors}}</td></tr>
    <tr><td>&nbsp;</td><td>
        <input type='button' name="signup_button" id="signup_button"
        value="Create my Account" onClick="javascript:signup(this.form);"/>
    </td></tr>
</table>
</form>

users/templates/stats.html
<div class="container georgia centeralign">
<ul class='stats'>
<li><a href="{%absurl colleges%}" target='_blank'>{{stats.colleges_count}} Colleges</a></li>
<li>{{stats.students_count}} Students</li>
<li><a href="{%absurl companies%}" target='_blank'>{{stats.companies_count}} Companies</a></li>
<li>{{stats.employees_count}} Employees</li>
<li>Joined Stud2.0 till now. So you are not alone! :D</li>
</ul>
</div>

users/templates/student_register.html
{%extends 'base.html'%}
{% block title %}Create a Student Account{% endblock %}
{%block content%}
<div class='prepend-6 prepend-top'>
    <h3 class='registration_or_login_header prepend-2 georgia'>Already have an Account ? <a href="{%url login%}">Please Login</a></h3>
    <form action="{%url student_register%}" method='POST' autocomplete="off">{% csrf_token %}
	<input type='hidden' name='next' value="{{next}}"/>
	<table class='form-table'>
	    <tr><td class='rightalign'><label for="id_email">Email :</label></td><td class='leftalign'>{{form.email}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.email.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_password">Password :</label></td><td class='leftalign'>{{form.password}}<span class='help_text'>(<span class='required'>Required</span>. Min of 6 characters. Max of 50 characters)</span><br/>{{form.password.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_name">Name :</label></td><td class='leftalign'>{{form.name}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.name.errors}}</td></tr>
	    <tr><td class='rightalign'><label for="id_college">College :</label></td><td class='leftalign'>{{form.college}}<span class='help_text'>(<span class='required'>Required</span>. Max of 100 characters)</span><br/>{{form.college.errors}}</td></tr>
	    <tr><td>&nbsp;</td><td><input class='btn primary' class='btn primary' type='submit' name='submit' value="Create my Account"/></td></tr>
	</table>
	</form>
</div>
{%endblock%}
{%block extrajs%}
<script type='text/javascript'>document.forms[0].email.focus();</script>
<script type='text/javascript' src="/site_media/js/jquery-ui/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type='text/javascript'>
$(document).ready(function(){
    var array = new Array();
    $('#id_college').autocomplete({
        dataType:'json',
        source:'{%url ajax_colleges_list%}',
        minLength:1,
    });
});
</script>
{%endblock%}
{%block extrastyle%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/js/jquery-ui/css/flick/jquery-ui-1.8.10.custom.css" />
{%endblock%}