quest/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('quest.views',
    (r'^$', 'view_questions', {'questions_template':'questions.html'}, 'all_questions'),#TODO:Url name 'all_questions' will be changed to 'questions'
    (r'^(?P<question_id>\d+)/giveanswer/$', 'view_give_answer', {'give_answer_template':'give_answer.html', 'question_template':'question.html'}, 'give_answer'),
    (r'^(?P<question_id>\d+)/acceptanswer/$', 'view_accept_answer', {'answers_template':'answers.html'}, 'accept_answer'),
    (r'^closeanswering/$', 'view_close_answering', {'question_template':'question.html', 'close_answer_template':'give_answer.html'}, 'close_answering'),
    (r'^(?P<question_id>\d+)/(?P<question_slug>[\w\s-]+)/$', 'view_question', {'question_template':'question.html'}, 'question'),
    (r'^(?P<question_id>\d+)/(?P<question_slug>[\w\s-]+)/edit/$', 'view_edit_question', {'edit_question_template':'ask_or_edit_question.html'}, 'edit_question'),
    (r'^ask/$', 'view_ask_question', {'ask_question_template':'ask_or_edit_question.html'}, 'ask_question'),
    (r'^(?P<tag_name>[\w.-]+)/$', 'view_tagged_questions', {'tagged_questions_template':'tagged_questions.html'}, 'tagged_questions'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.template import add_to_builtins

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^robots.txt$', 'django.views.generic.simple.direct_to_template', {
                'template': 'robots.txt' }),
    (r'^admin/', include(admin.site.urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^users/', include('users.urls')),
    (r'^questions/', include('quest.urls')),
    (r'^tasks/', include('tasks.urls')),
    (r'^utils/', include('utils.urls')),
)

urlpatterns += patterns('users.views',
    (r'^$', 'view_homepage', {'homepage_template':'homepage.html'}, 'homepage'),
    (r'^dashboard/$', 'view_dashboard', {'dashboard_template':'dashboard.html'}, 'dashboard'),
    (r'^notepad/$', 'view_notepad', {'notepad_template':'notepad.html'}, 'notepad'),
    (r'^webresume/$', 'view_webresume', {}, 'webresume'),
    (r'^invite/$', 'view_invite', {'invite_template':'invite.html'}, 'invite'),
    (r'^achievements/$', 'view_all_achievements', {'achievements_template':'achievements.html'}, 'achievements'),
)

urlpatterns += patterns('users.views',
    (r'^accounts/register/$', 'view_register', {'registration_template': 'register.html'}, 'register'),
    (r'^accounts/studentregister/$', 'view_register', {'registration_template': 'student_register.html', 'user_type':'S'}, 'student_register'),
    (r'^accounts/employeeregister/$', 'view_register', {'registration_template': 'employee_register.html', 'user_type':'E'}, 'employee_register'),
    (r'^accounts/professorregister/$', 'view_register', {'registration_template': 'professor_register.html', 'user_type':'P'}, 'professor_register'),
    (r'^accounts/login/$', 'view_login', {'login_template': 'login.html'}, 'login'),
    (r'^accounts/logout/$', 'view_logout', {'logout_template': 'logout.html'}, 'logout'),
    (r'^contactuser/(?P<user_id>\d+)/$', 'view_contactuser', {'contactuser_template':'contactuser.html'}, 'contactuser'),
    (r'^contactgroup/(?P<group_type>\w+)/(?P<group_id>\d+)/$', 'view_contactgroup', {'contactgroup_template':'contactgroup.html'}, 'contactgroup'),
    (r'^contactus/$', 'view_contactus', {'contactus_template':'contactus.html'}, 'contactus'),
    (r'^forgot_password/$', 'view_forgot_password', {'forgot_password_template':'forgot_password.html'}, 'forgot_password'),
    (r'^reset_my_password/$', 'view_reset_my_password', {'reset_my_password_template':'reset_my_password.html'}, 'reset_my_password'),
    (r'^add_achievement/$', 'view_add_achievement', {'add_achievement_template':'add_or_edit_achievement.html'}, 'add_achievement'),
    (r'^edit_achievement/(?P<achievement_id>\d+)/$', 'view_edit_achievement', {'edit_achievement_template':'add_or_edit_achievement.html'}, 'edit_achievement'),
)

urlpatterns += patterns('users.views',
    (r'^settings/$', 'view_account_settings', {'settings_template':'settings.html'}, 'settings'),
    (r'^settings/personal/$', 'view_save_personal_settings', {'personal_settings_template':'personal_settings.html'}, 'personal_settings'),
    (r'^settings/acad/$', 'view_save_acad_settings', {'acad_settings_template':'acad_settings.html'}, 'acad_settings'),
    (r'^settings/workinfo/$', 'view_save_workinfo_settings', {'workinfo_settings_template':'workinfo_settings.html'}, 'workinfo_settings'),                    
)

urlpatterns += patterns('users.views',
    (r'^colleges/$', 'view_colleges', {'colleges_template':'colleges.html'}, 'colleges'),
    (r'^colleges/(?P<college_id>\d+)/(?P<college_slug>[\w\s-]+)/$', 'view_college', {'college_template':'college.html'}, 'college_profile'),
)

urlpatterns += patterns('users.views',
    (r'^companies/$', 'view_all_companies', {'companies_template':'companies.html'}, 'companies'),
    (r'^companies/(?P<company_id>\d+)/(?P<company_slug>[\w\s-]+)/$', 'view_company', {'company_template':'company.html'}, 'company_profile'),
)

add_to_builtins('utils.templateutils')

quest/models.py
from django.db import models
from utils.models import BaseModel, BaseModelManager
from utils import slugify
from users.models import UserProfile
from taggit.managers import TaggableManager
from django.db.models.signals import post_save
from django.conf import settings

class QuestionAlreadyExistsException(Exception):
    pass

class AnswerCantBeAcceptedException(Exception):
    pass

class AnsweringIsClosedException(Exception):
    pass

class EmptyQuestionCantBeSavedException(Exception):
    pass

class QuestionManager(BaseModelManager):
    def create_question(self, title, description, userprofile, tags):
        if self.exists(slug=slugify(title)):
            raise QuestionAlreadyExistsException
        question = Question(title=title, slug=slugify(title),
                            description=description, raised_by=userprofile)
        question.save()
        question.tags.add(*tags)
        return question 
            
    def update_question(self, question, **attributes):
        if attributes:
            if attributes.has_key('title') and attributes.has_key('description') and attributes.get('title') and attributes.get('description'):
                if attributes.has_key('tags'):
                    tags = attributes.get('tags')
                    question.tags.clear()
                    question.tags.add(*tags)
                    attributes.pop('tags')
                for attr_label in attributes:
                    setattr(question, attr_label, attributes[attr_label])
                question.save()
                return 
        raise EmptyQuestionCantBeSavedException
    
class Question(BaseModel):
    title = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, db_index=True)
    description = models.CharField(max_length=1000, blank=True, null=True)#should clean tags.
    raised_by = models.ForeignKey(UserProfile)
    closed = models.BooleanField(default=False)
    objects = QuestionManager()
    tags = TaggableManager()
    
    def __unicode__(self):
        return "%s...." % self.title[:10]
    
    @property
    def answers(self):
        return self.answer_set.all()
    
    @property
    def owner(self):
        return self.raised_by
    
    @property
    def accepted_answer(self):
        if self.answers.filter(accepted=True).count():#since lazy fetching is allowed
            return self.answers.get(accepted=True)#there will only be one accepted answer for a question
        return None
    
    def close_answering(self):
        if not self.closed:
            self.closed = True
            self.save()
    
    def is_accepting_answers(self):
        if self.closed:
            return False
        return True
    
    def all_related_users_emails(self):
        emails = []
        emails.append(self.raised_by.user.email)
        for answer in self.answers:
            emails.append(answer.given_by.user.email)
        return set(emails)
    
class AnswerManager(BaseModelManager):
    def create_answer(self, question, description, userprofile, accepted=False):
        if question.closed:
            raise AnsweringIsClosedException
        if accepted and (question.raised_by.id != userprofile.id):
            raise AnswerCantBeAcceptedException
        if accepted:
            for previous_answer in question.answer_set.all():
                previous_answer.unaccept()
        answer = Answer(question=question,
                        description=description,
                        accepted=accepted,
                        given_by=userprofile)
        answer.save()
        return answer
    
class Answer(BaseModel):
    question = models.ForeignKey(Question)
    description = models.CharField(max_length=2000, blank=True, null=True)
    accepted = models.BooleanField(default=False)
    given_by = models.ForeignKey(UserProfile)
    objects = AnswerManager()
    
    def __unicode__(self):
        return "%s...." % self.description[:10]
    
    def unaccept(self):
        if self.accepted:
            self.accepted = False
            self.save()
    
    def accept(self, accepted_by):
        if not self.accepted:
            if self.question.raised_by.id != accepted_by.id:
                raise AnswerCantBeAcceptedException
            all_answers_for_the_question = self.question.answer_set.all()
            for answer in all_answers_for_the_question:
                answer.unaccept()
            self.accepted = True
            self.save()
            
def increment_question_points(sender, instance, **kwargs):
    if kwargs['created']:
        userprofile = instance.raised_by
        userprofile.award_score(settings.QUESTION_POINTS)

def increment_answer_points(sender, instance, **kwargs):
    if kwargs['created']:
        userprofile = instance.given_by 
        userprofile.award_score(settings.ANSWER_POINTS)
            
post_save.connect(increment_question_points, Question, dispatch_uid='increment_question_signal')
post_save.connect(increment_answer_points, Answer, dispatch_uid='increment_answer_signal')

quest/forms.py
from django import forms
from django.template.defaultfilters import removetags
from django.conf import settings
from utils.formfields import TagField, TagWidget
from utils.formfields import AutocompleteWidget

class AskQuestionForm(forms.Form):
    title = forms.CharField(max_length=80, required=True, widget=AutocompleteWidget(attrs={'size':'70'}))
    description = forms.CharField(max_length=1000, required=True, widget=forms.Textarea(attrs={'rows':10, 'cols':50}))
    tags = TagField(required=True, max_length=100, widget=TagWidget(attrs={'size':'70'}))
    
    def clean_description(self):
        description = self.cleaned_data.get('description')
        return removetags(description, settings.FILTER_HTML_TAGS)
    
class GiveAnswerForm(forms.Form):
    description = forms.CharField(max_length=2000, required=True, widget=forms.Textarea(attrs={'rows':10, 'cols':100, 'width':'300px'}))
    
    def clean_description(self):
        description = self.cleaned_data.get('description')
        return removetags(description, settings.FILTER_HTML_TAGS)

quest/templates/ajax_search_results.html
<ul>
{%for question in questions%}
    <li class='ajax_search_result'><a href="{{question.object.get_absolute_url}}">{{question.object.title}}</a></li>
{%empty%}
<li>No Results Found</li>
{%endfor%}
</ul>

quest/templates/all_questions.html
{%extends 'doublepane_base.html'%}
{%block title%}All Questions{%endblock%}
{%block questionstab%}activetab{%endblock%}
{%block feature_usage%}
<h3>Questions is a Bank of Questions and Answers. You can&nbsp;:</h3>
<ul>
    <li>Clearly know about things you are facing difficulty in understanding from the text book.</li>
    <li>Get opinions about you topic of interest from Industry Experts</li>
    {%if userprofile.is_student%}
    <li>If you are a Senior student, You can help out juniors by advising on the questions they raised</li>
    {%endif%} 
    <li>Ask a Question Gets you 3 points</li>
    <li>Answering a Question Gets you 5 points</li>
</ul>
{%endblock%}
{%block maincontent%}
<h2 class='georgia maincontent_header blue_underline'>All {%if tag%}{{tag.name|title}} {%endif%}Questions</h2>
{%for question in questions%}
<h3><a href="{%url question question.id question.slug%}" target='_blank'>{{question.title}}</a></h3>
{%endfor%}
{%endblock%}
{%block sidebar%}
<input id="ask_question_button" type='button' name='submit' value="Ask a Question" onClick='javascript:document.location.href="{%url ask_question%}"'/>
<br/>
<br/>
<br/>
<h3 class='special_blue'>Browse by Tag</h3>
<div id='all_tags_widget'>
<ul>
{%for tag in all_tags%}
	<li><a class="tag" title="Browse {{tag.name|title}} Questions" href="{%url tagged_questions tag_name=tag.name%}">{{tag.name}}</a></li>
{%endfor%}
</ul>
</div>
{%endblock%}

quest/templates/answers.html
{%load users_tags%}
{%for answer in all_answers%}
    {%with answer.accepted as accepted_answer%}
    <div class='answer_block {%if accepted_answer%}accepted_answer{%endif%}' {%if accepted_answer%}title='This is the Final Answer'{%endif%}>
        {%autoescape off%}
            {{answer.description|removetags:"script button input marquee"}}<br/>
        {%endautoescape%}
        <span class='small_text'>Posted by {%with answer.given_by as given_by%}{%render_user_domain given_by%}{%endwith%} on {{answer.created_on|date:"dS M Y g:i A"}}</span>
        {%if not accepted_answer%}
            {%ifequal question.raised_by.id userprofile.id%}
                <br/><br/><input type="button" class="btn primary" value="Make this as final answer" name="accept_answer" onClick="javascript:accept_answer('{{question.id}}','{{answer.id}}');"/><br/>
            {%endifequal%}
        {%endif%}
    </div>
    {%endwith%}
{%endfor%}

quest/templates/ask_or_edit_question.html
{%extends 'doublepane_base.html'%}
{%block title%}{%if question%}Edit{%else%}Ask{%endif%} a Question{%endblock%}
{%block maincontent%}
<div class='feature_usage prepend-top box'>
    <div id='close' onClick='javascript:$(".feature_usage").fadeOut();' class='right' title="Hide this Help">&nbsp;&nbsp;</div>
<h3>Benifits of asking a Question:</h3>
<ul>
    <li>Let your Senior or an Industry Expert help you in solving a problem</li>
    <li>Show your skills by asking questions on topics you know</li>
    {%if question%}
    <li>Answering a Question Gets you 5 points</li>
    {%else%}
    <li>Asking a Question Gets you 3 points</li>
    {%endif%}
</ul>
</div><!-- end of feature_usage -->
<h3 class='georgia maincontent_header blue_underline'>{%if question%}Edit{%else%}Ask{%endif%} a Question</h3>
<form action="{%if question%}{%url edit_question question.id question.slug%}{%else%}{%url ask_question%}{%endif%}" method='POST' autocomplete='off'>{% csrf_token %}
<table class='form-table'>
    <tr><td class='rightalign'><label for="id_title">Question :</label></td><td class='leftalign'>{{form.title}}<span class='help_text'>(<span class='required'>Required</span>. Max of 80 characters)</span><br/><span class='help_text'>Ex:Ask about a <span class="special_blue bold">Project Idea</span>, Ask about a <span class="special_blue bold">Technology</span>, Ask <span class="special_blue bold">anything!</span></span><br/>{{form.title.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_description">Description :</label></td><td class='leftalign'>{{form.description}}<br/><span class='help_text'>(<span class='required'>Required</span>. Max of 1000 characters)</span>&nbsp;&nbsp;<span id='status_meter_id' class='small_text'></span><br/>{{form.description.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_tags">Tags</label></td><td class='form-row'>{{form.tags}}<br/><span class='help_text'>(<span class='required'>Required</span>. Mention multiple tags separated by commas. Avoid spaces in tags.)</span>{{form.tags.errors}}</td></tr>
    <tr><td>&nbsp;</td><td><input type='submit' class='btn primary' name='submit' value="{%if question%}Save{%else%}Submit{%endif%} Question"/></td></tr>
</table>
</form>
{%endblock%}
{%block sidebar%}
{%if question%}
    <h4 class='georgia widget_header'>Your previous questions</h4>
    {%if previous_questions%}
        <ul>
        {%for pquestion in previous_questions%}
        <li><a href="{%url question pquestion.id pquestion.slug%}" target='_blank'>{{pquestion.title|truncatewords:3}}</a></li>
        {%endfor%}
        </ul>
    {%else%}
        No other Questions asked yet!
    {%endif%}
{%else%}
    <h4 class='georgia widget_header'>Your previous questions</h4>
    {%if asked_questions%}
        <ul>
        {%for pquestion in asked_questions%}
        <li><a href="{%url question pquestion.id pquestion.slug%}" target='_blank'>{{pquestion.title|truncatewords:3}}</a></li>
        {%endfor%}
        </ul>
    {%else%}
        No Questions asked yet!
    {%endif%}
{%endif%}
{%endblock%}
{%block extrajs%}
<script type='text/javascript'>
document.forms[0].title.focus();
$('#id_description').keyup(function(e){
    charCounter({{form.fields.description.max_length}}, 'id_description', 'status_meter_id');
    });
</script>
<script type='text/javascript' src="/site_media/js/jquery-ui/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type='text/javascript'>
    autocomplete_bind('#id_tags', '{%url ajax_tags_list%}');
    autocomplete_bind('#id_title', '{%url ajax_questions_list%}', true);
</script>    
{%endblock%}
{%block extrastyle%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/js/jquery-ui/css/flick/jquery-ui-1.8.10.custom.css" />
{%endblock%}

quest/templates/ask_question.html
{%extends 'singlepane_base.html'%}
{%block title%}Ask a Question{%endblock%}
{%block content%}
<div class='prepend-6'>
    <form action="{%url ask_question%}" method='POST'>{% csrf_token %}
    <table class='form-table'>
        <tr><td class='rightalign'><label for="id_title">Question :</label></td><td class='leftalign'>{{form.title}}<span class='help_text'>(<span class='required'>Required</span>. Max of 80 characters)</span><br/>{{form.title.errors}}</td></tr>
        <tr><td class='rightalign'><label for="id_description">Description :</label></td><td class='leftalign'>{{form.description}}<span class='help_text'>(<span class='required'>Required</span>. Max of 1000 characters)</span><br/>{{form.description.errors}}</td></tr>
        <tr><td>&nbsp;</td><td><input type='submit' name='submit' value="Submit Question"/></td></tr>
    </table>
    </form>
</div>
{%endblock%}
{%block extrajs%}<script type='text/javascript'>document.forms[0].title.focus();</script>{%endblock%}

quest/templates/email_question.html
{%extends 'base.html'%}
{%block title%}Email this Question{%endblock%}
{%block content%}
<div class='prepend-6'>
<!-- here goes email form -->
</div>
{%endblock%}
{%block extrajs%}<script type='text/javascript'>document.forms[0].title.focus();</script>{%endblock%}

quest/templates/existing_answers.html
{%with question.answers as all_answers%}
<div id='all_answers'>
{%include 'answers.html'%}
</div><!-- end of all_answers -->
{%endwith%}

quest/templates/give_answer.html
{%if give_answer_form%}
<form action="{%url give_answer question.id %}" method='POST'>{% csrf_token %}
{{give_answer_form.question}}
<h3>Want to Suggest an Answer ? Please answer!</h3>
<li>Answering a Question Gets you 5 points</li>
<table>
    <tr><td class='leftalign'>{{give_answer_form.description}}<br/><span class='help_text'>(<span class='required'>Required</span>. Max of 2000 characters)</span>&nbsp;&nbsp;<span id='status_meter_id' class='small_text'></span><br/>{{give_answer_form.description.errors}}</td></tr>
    <tr><td><input class='btn primary' type='submit' name='submit' value="Submit Your Answer" onClick="javascript:return confirm('Are you sure you want to submit the answer now ?');"/></td></tr>
</table>
</form>
{%else%}
<h3>Answers are Closed</h3>
{%endif%}

quest/templates/question.html
{%extends 'doublepane_base.html'%}
{%block title%}{{question.title}}{%endblock%}
{%block questionstab%}activetab{%endblock%}
{%block content%}
{%load users_tags%}
<div id='question_body' class='span18 column'>
<h2><a href="{%url question question.id question.slug%}">{{question.title}}</a></h2>

<div id='question_description'>{%autoescape off%}{{question.description}}{%endautoescape%}</div>
<div id='question_action_links'>

<span class='small_text'>Posted by {%with question.raised_by as raised_by%}{%render_user_domain raised_by %}{%endwith%} on {{question.modified_on|date:"dS F Y"}}</span>
{%with question.tags as tags %}
{%if tags.count%}
	<span class='small_text'> in </span>&nbsp;&nbsp;{%for tag in tags.all%}
	<a class="tag" title="Browse {{tag.name|title}} Questions" href="{%url tagged_questions tag_name=tag.name%}">{{tag.name}}</a>
	{%endfor%}
{%endif%}
{%endwith%}
<br/>
</div>
    {%if not question.closed and userprofile.id == question.owner.id %}
        <br/><input class='btn primary' type='button' onClick='javascript:close_answering("{{question.id}}")' value='Close Answering' name='close_answering'/>    
    {%endif%}
    {%include 'existing_answers.html'%}
<div id='give_answer_section'>
    {%include 'give_answer.html'%}
</div><!-- end of give_answer_section -->
</div>
{%endblock%}
{%block sidebar%}
<h3>Share</h3>
<!-- AddThis Button BEGIN -->
<div id="share_question_links" class="addthis_toolbox addthis_default_style ">
&nbsp;&nbsp;|&nbsp;&nbsp;<a title="Link to this question" href="{%url question question.id question.slug%}">Link</a>&nbsp;&nbsp;
{%if userprofile.id == question.owner.id%}|&nbsp;&nbsp;<a title="Edit this question" href="{%url edit_question question.id question.slug%}">Edit</a>&nbsp;&nbsp;{%endif%}
<a href="http://www.addthis.com/bookmark.php?v=250&amp;username=madhavbnk" class="addthis_button_compact">Share</a>
<span class="addthis_separator">|</span>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
</div>
<!-- AddThis Button END -->
{%endblock%}
{%block extrajs%}
<script type='text/javascript' src='/site_media/js/questions.js'></script>
<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=madhavbnk"></script>
<script type="text/javascript">
$('#id_description').keyup(function(e){
    charCounter({{give_answer_form.fields.description.max_length}}, 'id_description', 'status_meter_id');
});
</script>
{%endblock%}

quest/templates/questions.html
{%extends 'base.html'%}
{%block title%}Questions{%endblock%}
{%block questionstab%}activetab{%endblock%}
{%block content%}
<div class='feature_usage prepend-top box'>
    <div id='close' onClick='javascript:$(".feature_usage").fadeOut();' class='right' title="Hide this Help">&nbsp;&nbsp;</div>
    <h3>Questions is a Bank of Questions and Answers. You can&nbsp;:</h3>
    <ul>
        <li>Clearly know about things you are facing difficulty in understanding from the text book.</li>
        <li>Get opinions about you topic of interest from Industry Experts</li>
        {%if userprofile.is_student%}
        <li>If you are a Senior student, You can help out juniors by advising on the questions they raised</li>
        {%endif%} 
        <li>Ask a Question Gets you 3 points</li>
        <li>Answering a Question Gets you 5 points</li>
        <li>Raise a <span class='special_blue bold'>Project Idea</span> and let People <span class='special_blue bold'>help you</span> by giving their feedback</li>
    </ul>
</div><!-- end of feature_usage -->
<div class='centeralign'>
<span id="search_question" class='bold'>Search : <input type="text" id='id_question_title' name="term" size="80" style='padding:4px;font-size:1.25em;'/></span>&nbsp;(&nbsp;or&nbsp;)&nbsp;<input id="ask_question_button" class='btn primary' type='button' name='submit' value="Ask a Question" onClick='javascript:document.location.href="{%url ask_question%}"'/>
<h3 id='search_questions_header' class='georgia maincontent_header'>Browse all {{questions_count}} Questions by Tags</h3>
<ul id='all_tags_widget' style='width:80%;'>
{%for tag in all_tags%}
	<li><a class="tag" title="Browse {{tag.name|title}} Questions" href="{%url tagged_questions tag_name=tag.name%}">{{tag.name}}</a></li>
{%endfor%}
</ul>
</div>
{%endblock%}
{%block extrajs%}
<script type='text/javascript' src="/site_media/js/jquery-ui/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type='text/javascript'>
    autocomplete_bind('#id_question_title', '{%url ajax_questions_list%}', true);
</script>    
{%endblock%}
{%block extrastyle%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/js/jquery-ui/css/flick/jquery-ui-1.8.10.custom.css" />
{%endblock%}

quest/templates/tagged_questions.html
{%extends 'base.html'%}
{%block title%}All Questions{%endblock%}
{%block questionstab%}activetab{%endblock%}
{%block content%}
<div class='feature_usage prepend-top box'>
    <div id='close' onClick='javascript:$(".feature_usage").fadeOut();' class='right' title="Hide this Help">&nbsp;&nbsp;</div>
<h3>Questions is a Bank of Questions and Answers. You can&nbsp;:</h3>
<ul>
    <li>Clearly know about things you are facing difficulty in understanding from the text book.</li>
    <li>Get opinions about you topic of interest from Industry Experts</li>
    {%if userprofile.is_student%}
    <li>If you are a Senior student, You can help out juniors by advising on the questions they raised</li>
    {%endif%} 
    <li>Ask a Question Gets you 3 points</li>
    <li>Answering a Question Gets you 5 points</li>
</ul>
</div><!-- end of feature_usage -->
<h2 class='georgia maincontent_header blue_underline'>All {%if tag%}{{tag.name|title}} {%endif%}Questions</h2>
{%for question in questions%}
<h3><a href="{%url question question.id question.slug%}" target='_blank'>{{question.title}}</a></h3>
{%endfor%}
{%endblock%}
{%block sidebar%}
<input class='btn primary' id="ask_question_button" type='button' name='submit' value="Ask a Question" onClick='javascript:document.location.href="{%url ask_question%}"'/>
<br/>
<br/>
<br/>
<h3 class='special_blue'>Browse by Tag</h3>
<div id='all_tags_widget'>
<ul>
{%for tag in all_tags%}
	<li><a class="tag" title="Browse {{tag.name|title}} Questions" href="{%url tagged_questions tag_name=tag.name%}">{{tag.name}}</a></li>
{%endfor%}
</ul>
</div>
{%endblock%}