urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.template import add_to_builtins

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^robots.txt$', 'django.views.generic.simple.direct_to_template', {
                'template': 'robots.txt' }),
    (r'^admin/', include(admin.site.urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    (r'^users/', include('users.urls')),
    (r'^questions/', include('quest.urls')),
    (r'^tasks/', include('tasks.urls')),
    (r'^utils/', include('utils.urls')),
)

urlpatterns += patterns('users.views',
    (r'^$', 'view_homepage', {'homepage_template':'homepage.html'}, 'homepage'),
    (r'^dashboard/$', 'view_dashboard', {'dashboard_template':'dashboard.html'}, 'dashboard'),
    (r'^notepad/$', 'view_notepad', {'notepad_template':'notepad.html'}, 'notepad'),
    (r'^webresume/$', 'view_webresume', {}, 'webresume'),
    (r'^invite/$', 'view_invite', {'invite_template':'invite.html'}, 'invite'),
    (r'^achievements/$', 'view_all_achievements', {'achievements_template':'achievements.html'}, 'achievements'),
)

urlpatterns += patterns('users.views',
    (r'^accounts/register/$', 'view_register', {'registration_template': 'register.html'}, 'register'),
    (r'^accounts/studentregister/$', 'view_register', {'registration_template': 'student_register.html', 'user_type':'S'}, 'student_register'),
    (r'^accounts/employeeregister/$', 'view_register', {'registration_template': 'employee_register.html', 'user_type':'E'}, 'employee_register'),
    (r'^accounts/professorregister/$', 'view_register', {'registration_template': 'professor_register.html', 'user_type':'P'}, 'professor_register'),
    (r'^accounts/login/$', 'view_login', {'login_template': 'login.html'}, 'login'),
    (r'^accounts/logout/$', 'view_logout', {'logout_template': 'logout.html'}, 'logout'),
    (r'^contactuser/(?P<user_id>\d+)/$', 'view_contactuser', {'contactuser_template':'contactuser.html'}, 'contactuser'),
    (r'^contactgroup/(?P<group_type>\w+)/(?P<group_id>\d+)/$', 'view_contactgroup', {'contactgroup_template':'contactgroup.html'}, 'contactgroup'),
    (r'^contactus/$', 'view_contactus', {'contactus_template':'contactus.html'}, 'contactus'),
    (r'^forgot_password/$', 'view_forgot_password', {'forgot_password_template':'forgot_password.html'}, 'forgot_password'),
    (r'^reset_my_password/$', 'view_reset_my_password', {'reset_my_password_template':'reset_my_password.html'}, 'reset_my_password'),
    (r'^add_achievement/$', 'view_add_achievement', {'add_achievement_template':'add_or_edit_achievement.html'}, 'add_achievement'),
    (r'^edit_achievement/(?P<achievement_id>\d+)/$', 'view_edit_achievement', {'edit_achievement_template':'add_or_edit_achievement.html'}, 'edit_achievement'),
)

urlpatterns += patterns('users.views',
    (r'^settings/$', 'view_account_settings', {'settings_template':'settings.html'}, 'settings'),
    (r'^settings/personal/$', 'view_save_personal_settings', {'personal_settings_template':'personal_settings.html'}, 'personal_settings'),
    (r'^settings/acad/$', 'view_save_acad_settings', {'acad_settings_template':'acad_settings.html'}, 'acad_settings'),
    (r'^settings/workinfo/$', 'view_save_workinfo_settings', {'workinfo_settings_template':'workinfo_settings.html'}, 'workinfo_settings'),                    
)

urlpatterns += patterns('users.views',
    (r'^colleges/$', 'view_colleges', {'colleges_template':'colleges.html'}, 'colleges'),
    (r'^colleges/(?P<college_id>\d+)/(?P<college_slug>[\w\s-]+)/$', 'view_college', {'college_template':'college.html'}, 'college_profile'),
)

urlpatterns += patterns('users.views',
    (r'^companies/$', 'view_all_companies', {'companies_template':'companies.html'}, 'companies'),
    (r'^companies/(?P<company_id>\d+)/(?P<company_slug>[\w\s-]+)/$', 'view_company', {'company_template':'company.html'}, 'company_profile'),
)

add_to_builtins('utils.templateutils')

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import UserProfile, branches
import re
from users.messages import WEBRESUME_FIELD_HOVER
from users.messages import COLLEGE_FIELD_HOVER_FOR_EMP_SIGNUP
from users.messages import AGGREGATE_HOVER
from utils.formfields import MultipleEmailsField, AutocompleteWidget
from django.conf import settings

USER_NAME_CLEANUP_REGEX_PATTERN = re.compile(r'[^\w.&\s-]+', re.IGNORECASE)
USER_SLUG_DOMAIN_CLEANUP_REGEX_PATTERN = re.compile(r'%s' % settings.DOMAIN, re.IGNORECASE)
USER_SLUG_CLEANUP_REGEX_PATTERN = re.compile(r'[^a-zA-Z0-9]', re.IGNORECASE)
COLLEGE_NAME_CLEANUP_REGEX_PATTERN = re.compile(r'[^\w.&\s-]+', re.IGNORECASE) 
FILENAME_FILTER_REGEXT = '[^.]'
MIN_COLLEGE_START_YEAR = 1910
MIN_COLLEGE_END_YEAR = 1912
MAX_COLLEGE_START_YEAR = 2011
MAX_COLLEGE_END_YEAR = 2015
COLLEGE_START_YEAR_RANGE = tuple([(year, year) for year in range(MIN_COLLEGE_START_YEAR, MAX_COLLEGE_START_YEAR + 1)]) 
COLLEGE_END_YEAR_RANGE = tuple([(year, year) for year in range(MIN_COLLEGE_END_YEAR, MAX_COLLEGE_END_YEAR + 1)])
YEARS_OF_EXP_CLEANUP_REGEX_PATTERN = re.compile(r'^\d+([\.]\d[\d]*)*$')

class UserSignupForm(forms.Form):
    email = forms.EmailField(max_length=50, required=True)
    password = forms.CharField(min_length=6, max_length=50, required=True, widget=forms.PasswordInput())
    name = forms.CharField(max_length=50, required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            UserProfile.objects.get(user__email=email)
            raise ValidationError('Email Already Picked!')
        except UserProfile.DoesNotExist:
            return email
        
class StudentSignupForm(UserSignupForm):
    college = forms.CharField(required=True, max_length=100, widget=AutocompleteWidget())
    
class EmployeeSignupForm(UserSignupForm):
    company = forms.CharField(required=True, max_length=50)
    college = forms.CharField(required=False, max_length=100,
            widget=forms.TextInput(attrs={'title':COLLEGE_FIELD_HOVER_FOR_EMP_SIGNUP}))
    
class ProfessorSignupForm(UserSignupForm):
    college = forms.CharField(required=True, max_length=100)

class UserLoginForm(forms.Form):
    email = forms.EmailField(max_length=50, required=True, widget=forms.TextInput(attrs={'tabindex':1}))
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={'tabindex':2}))
    
class SaveNoteForm(forms.Form):
    name = forms.CharField(max_length=30, required=True)
    short_description = forms.CharField(max_length=50, required=False)
    content = forms.CharField(max_length=7000, required=True, widget=forms.Textarea())
    public = forms.BooleanField(required=False, initial=True)
    
    def clean_content(self):
        return self.cleaned_data.get('content').strip()
    
class PersonalSettingsForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    slug = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'title':WEBRESUME_FIELD_HOVER}))
    new_password = forms.CharField(min_length=6, max_length=50, required=False, widget=forms.PasswordInput())
    
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise ValidationError('Please Enter a Valid Name')
        name = re.sub(USER_NAME_CLEANUP_REGEX_PATTERN, '', name)
        if not name.strip():
            raise ValidationError('Please Enter a Valid Name')
        return name
    
    def clean_slug(self):
        slug = self.cleaned_data.get('slug')
        slug = re.sub(USER_SLUG_DOMAIN_CLEANUP_REGEX_PATTERN, '', slug)
        if slug == re.sub(USER_SLUG_CLEANUP_REGEX_PATTERN, '', slug):
            return slug
        raise ValidationError('Please choose a Valid Web Resume Url. Should only contain alphabets and/or numbers')
    
    def masquerade_slug(self):
        #TODO:The goal is to show editable slug field only once.
        #so {{form.slug}} should be dynamic enough to render as a 
        #editable text field first time and as a simple label from second time.  
        raise NotImplementedError

class AcadSettingsForm(forms.Form):
    branch = forms.ChoiceField(required=True,
                               choices=((('', '-- Select --'),) + branches + (('-', '-- Other --'),)))
    college = forms.CharField(required=True, max_length=100)
    start_year = forms.ChoiceField(required=False, choices=COLLEGE_START_YEAR_RANGE)
    end_year = forms.ChoiceField(required=False, choices=COLLEGE_END_YEAR_RANGE)
    aggregate = forms.DecimalField(required=False, max_digits=3, decimal_places=1, widget=forms.TextInput(attrs={'title':AGGREGATE_HOVER}))
    
    def clean_college(self):
        college = self.cleaned_data.get('college')
        cleaned_college = re.sub(COLLEGE_NAME_CLEANUP_REGEX_PATTERN, '', college)
        if college != cleaned_college:
            raise ValidationError('Please choose a Valid college name. It cannot contain special symbols other than dot, hyphen, underscore')
        return cleaned_college

class WorkInfoSettingsForm(forms.Form):
    workplace = forms.CharField(required=True, max_length=100)
    designation = forms.CharField(required=False, max_length=50)
    years_of_exp = forms.CharField(required=False, max_length=5)
    
    def clean_workplace(self):
        workplace = self.cleaned_data.get('workplace')
        cleaned_workplace = re.sub(COLLEGE_NAME_CLEANUP_REGEX_PATTERN, '', workplace)
        if workplace != cleaned_workplace:
            raise ValidationError('Please choose a Valid Work Place name. It cannot contain special symbols other than dot, hyphen, underscore')
        return cleaned_workplace
    
    def clean_years_of_exp(self):
        years_of_exp = self.cleaned_data.get('years_of_exp')
        if re.match(YEARS_OF_EXP_CLEANUP_REGEX_PATTERN, years_of_exp):
            return years_of_exp
        raise ValidationError('Please enter Valid years of Experience. It should be of the format YY.MM')
    
class ContactForm(forms.Form):
    subject = forms.CharField(required=False, max_length=100)
    message = forms.CharField(max_length=500, required=True, widget=forms.Textarea())
    
class ContactUserForm(ContactForm):
    to = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'readonly':True}))

class ContactGroupForm(ContactForm):
    to = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'readonly':True}))
    
class ContactUsForm(ContactForm):
    from_name = forms.CharField(required=False, max_length=50)
    from_email = forms.EmailField(max_length=50, required=True)
    
class InvitationForm(forms.Form):
    to_emails = MultipleEmailsField(max_length=500, required=True)
    
class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(required=True, max_length=50)
    
class ResetMyPasswordForm(forms.Form):
    password = forms.CharField(min_length=6, max_length=50, required=True, widget=forms.PasswordInput())
    
class AddAchievementForm(forms.Form):
    title = forms.CharField(required=True, max_length=100)
    description = forms.CharField(required=True, max_length=7000, widget=forms.Textarea(attrs={'rows':10, 'cols':50}))

templates/achievements_tour.html
<div id='achievements_icon' class='tour_bigicon left'>
</div><!-- end of achievements_icon -->
<h2 class='tour_bigheader centeralign'>Achievements tell the world what <span
        class='orange_underline'>you are capable of</span></h2>
<div class='clear'></div>
<hr class='separate_ruler'/>
<h3 class='tour_subheader'>Tell about all your accomplished Projects</h3>
    <div id='add_note_image' class='right rightalign'>
    </div>
    <ul class='tour_points'>
        <li>Blah Blah Blah</li>
    </ul>    
<br/>
<h3 class='tour_subheader'>Boost your resume with real Achievements</h3>
<ul class='tour_points'>
    <li>Blah Blah Blah</li>
</ul>    

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{% block title %}{% endblock %} - Stud2.0</title>
{%block css%}
{%if debug%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/bootstrap/bootstrap.css"/>
{%else%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/bootstrap/bootstrap.min.css"/>
{%endif%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/css/master.css"/>
{%endblock%}
{%block extrastyle%}
{%endblock%}
</head>
<body>
    <div class='container'>
<header>
{%include 'header.html'%}
</header>
<div class='content'>
    {%block content%}
    {%endblock%}
</div><!-- end of content -->
<footer class='center'>
{%include 'footer.html'%}
{%if debug%}
<script type='text/javascript' src='/site_media/js/jquery/jquery-1.6.min.js'></script>
{%else%}
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js'></script>
{%endif%}
<script type='text/javascript' src='/site_media/js/common.js'></script>
<script type='text/javascript'>if($('.messages')){$('.messages').fadeOut(8000);}</script>
<script type='text/javascript' src='/site_media/bootstrap/js/bootstrap-twipsy.js'></script>
<script type='text/javascript' src='/site_media/bootstrap/js/bootstrap-dropdown.js'></script>
<script type='text/javascript'>
$(document).ready(function () {
    $('.topbar-menus').dropdown();
});
</script>
<script type='text/javascript'>
    $(function(){
       tooltip_icons = $('.tooltip').twipsy({title:'title', gravity:'s',fade:true});
       $('#id_slug').twipsy({trigger:'focus', title:'title', gravity:'n'});
       $('form').submit(function(){
           submit_button = $('input[type=submit]')[0];
           submit_button.value = 'Please Wait...';
           submit_button.disabled = true;
           return true;
           });
    });
</script>
{%block extrajs%}{%endblock%}
{%if not debug%}
{%include 'google_analytics.html'%}
{%endif%}
</footer>
    </div>
</body>
</html>

templates/contactus.html
{%extends 'base.html'%}
{% block title %}Contact Stud2.0 Team{% endblock %}
{%block content%}
<div id="contactus">
<h2 class='georgia maincontent_header blue_underline'>Contact Stud2.0 Team</h2>
<form action="{%url contactus%}" method="POST">{% csrf_token %}
<table>
    <tr><td class='rightalign'><label for="id_from_name">Your Name:</label></td><td class='leftalign'>{{form.from_name}}<span class='help_text'>(<span class='optional'>Optional</span>. Max of 50 characters)</span></td></tr>
    <tr><td class='rightalign'><label for="id_from_email">Your Email:</label></td><td class='leftalign'>{{form.from_email}}<span class='help_text'>(<span class='required'>Required</span>. Max of 50 characters)</span><br/>{{form.from_email.errors}}</td></tr>
    <tr><td class='rightalign'><label for="id_subject">Subject :</label></td><td class='leftalign'>{{form.subject}}<span class='help_text'>(<span class='optional'>Optional</span>. Max of 100 characters)</span></td></tr>
    <tr><td class='rightalign'><label for="id_message">Message :</label></td><td class='leftalign'>{{form.message}}<span class='help_text'>(<span class='required'>Required</span>. Max of 500 characters)</span><br/>{{form.message.errors}}</td></tr>
    <tr><td class='rightalign'>&nbsp;</td><td><input type="button" class="btn primary" value="Send Message"/></td></tr>
</table>
</form>
</div>
{%endblock%}

templates/doublepane_base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{% block title %}{% endblock %} - Stud2.0</title>
{%block css%}
{%if debug%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/bootstrap/bootstrap.css"/>
{%else%}
<link rel="stylesheet" type="text/css" media="screen, projection" href="/site_media/bootstrap/bootstrap.min.css"/>
{%endif%}
<style type='text/css'>
.content{padding-top:50px;}
.topbar-menus{font-size:16px;}
.topbar-menus > li{padding-left:30px;}
a#logo{font-size:24px;}
#lefttopbar > li{padding-left:30px;}
#righttopbar > li{padding-left:10px;}
</style>
{%endblock%}
{%block extrastyle%}
{%endblock%}
</head>
<body>
<header>
{%include 'header.html'%}
</header>
<div class='content'>
    <div class='container'>
        <div class='row'>
            <div class='span12'>
            {%block content%}
            {%endblock%}
            </div>
            <div class='span4'>
            {%block sidebar%}
            {%endblock%}
            </div>
        </div>
    </div>
</div><!-- end of content -->
<footer>
{%include 'footer.html'%}
{%if debug%}
<script type='text/javascript' src='/site_media/js/jquery/jquery-1.6.min.js'></script>
{%else%}
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js'></script>
{%endif%}
<script type='text/javascript' src='/site_media/js/common.js'></script>
<script type='text/javascript'>if($('.messages')){$('.messages').fadeOut(8000);}</script>
<script type='text/javascript' src='/site_media/bootstrap/js/bootstrap-twipsy.js'></script>
<script type='text/javascript' src='/site_media/bootstrap/js/bootstrap-dropdown.js'></script>
<script type='text/javascript'>
$(document).ready(function () {
    $('.topbar-menus').dropdown();
});
</script>
<script type='text/javascript'>
    $(function(){
       tooltip_icons = $('.tooltip').twipsy({title:'title', gravity:'s',fade:true});
       $('#id_slug').twipsy({trigger:'focus', title:'title', gravity:'n'});
       $('form').submit(function(){
           submit_button = $('input[type=submit]')[0];
           submit_button.value = 'Please Wait...';
           submit_button.disabled = true;
           return true;
           });
    });
</script>
{%block extrajs%}{%endblock%}
{%include 'google_analytics.html'%}
</footer>
</body>
</html>

templates/feature_usage.html
<div class='feature_usage prepend-top box'>
<div id='close' onClick='javascript:$(".feature_usage").fadeOut();' class='right' title="Hide this Help">&nbsp;&nbsp;</div>
{%block feature_usage%}
{%endblock%}
</div><!-- end of feature_usage -->

templates/footer.html
Stud2.0 &copy; 2012
&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="http://twitter.com/stud2dotoh/" target="_blank">Follow us on Twitter</a>
&nbsp;&nbsp;|&nbsp;&nbsp;
Need help? <a href="{%absurl contactus%}">Contact us</a>
&nbsp;&nbsp;|&nbsp;&nbsp;
<a href='http://stud2dotoh.com/site_media/html/aboutus.html'>About</a>
&nbsp;&nbsp;|&nbsp;&nbsp;
<a href='http://stud2dotoh.com/site_media/html/faq.html'>FAQ</a>

templates/google_analytics.html
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22325032-1']);
  _gaq.push(['_setDomainName', '.stud2dotoh.com']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

templates/header.html
<div class='topbar'>
    <div class='fill'>
        <div class='container'>
            <a id='logo' class='brand' href='/'>Stud<span style='color:#049cdb;margin-left:4px;'>2.0</span></a>
                <div class='pull-left'>
                    <ul id='lefttopbar' class='topbar-menus'>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">Tasks</a>
                            <ul class="dropdown-menu">
                                <li><a href='/tasks/'>Explore Tasks</a></li>
                                <li><a href='/tasks/popular/'>Popular Tasks</a></li>
                            </ul>
                        </li>    
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">You</a>
                            <ul class="dropdown-menu">
                                <li><a href='/tasks/my/'>Your Tasks</a></li>
                                <li><a href='/notes/my/'>Your Notes</a></li>
                                <li><a href='/questions/my/'>Your Q & A</a></li>
                                <li><a href='/rank/'>Your Rank</a></li>
                                <li><a href='/webresume/'>Your Resume</a></li>
                            </ul>
                        </li>    
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">Questions</a>
                            <ul class="dropdown-menu">
                                <li><a href='{% url all_questions %}'>Explore Questions</a></li>
                                <li><a href='{% url ask_question %}'>Ask a Question</a></li>
                                <li><a href='{% url all_questions %}'>Answer a Question</a></li>
                            </ul>
                        </li>    
                    </ul>
                </div><!-- end of lefttopbar items -->
                <div class='pull-right'>
                    <ul id='righttopbar' class='topbar-menus'>
                    {%if user.is_authenticated%}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">Settings</a>
                            <ul class="dropdown-menu">
                                <li><a href='/settings/personal/'>Pesonal</a></li>
                                <li><a href='/settings/acadinfo/'>Academic</a></li>
                                <li><a href='/settings/workinfo/'>Work</a></li>
                            </ul>
                        </li>    
                       <li><a href='{%absurl logout%}'>Logout</a></li>
                    {%else%}
                       <li><a href='{%absurl register%}'>SignUp</a></li>
                       <li><a href='{%absurl login%}'>Login</a></li>
                    {%endif%}
                       <li><a href="{%absurl invite%}">Invite</a></li>
                    </ul>
                </div><!-- end of righttopbar items -->
        </div><!-- end of container -->
    </div><!-- end of fill -->
</div><!-- end of topbar -->

templates/messages_bar.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{%autoescape off%}{{ message }}{%endautoescape%}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/notepad_tour.html
<div id='notepad_icon' class='tour_bigicon left'>
</div><!-- end of notepad_icon -->
<h2 class='tour_bigheader centeralign'>Notepad is a Quick way to Save anything <span
        class='orange_underline'>online</span> quickly</h2>
<div class='clear'></div>
<hr class='separate_ruler'/>
<h3 class='tour_subheader'>Save anything</h3>
    <div id='add_note_image' class='right rightalign'>
    </div>
    <ul class='tour_points'>
        <li>College Assignment(for Students)</li>
        <li>Lab Programs(for Students)</li>
        <li>Thesis Paper Notes(for Students)</li>
        <li>Any content which you want to Bookmark</li>
        <li>Thesis Paper Notes(for Students)</li>
    </ul>    
<br/>
<h3 class='tour_subheader'>Share &amp; Benifit</h3>
<ul class='tour_points'>
    <li>Impress anyone looking at your Resume with your Notes</li>
    <li>Lets the world know what you know</li>
    <li>Every Note saved gets you 3 points</li>
</ul>    

templates/pagination.html
{%if previous_page_number%}
<a class="previous_page" href='?page={{previous_page_number}}'>Previous</a>
{%endif%}
<span class="current_page">Page {{current_page_number}}</span>
{%if next_page_number%}
<a class="next_page" href='?page={{next_page_number}}'>Next Page</a>
{%endif%}

templates/qanda_tour.html
<div id='qanda_icon' class='tour_bigicon left'>
</div><!-- end of qanda_icon -->
<h2 class='tour_bigheader centeralign'>Questions & Answers help you <br/><span
        class='orange_underline'>get clarified and share knowledge</span></h2>
<div class='clear'></div>
<hr class='separate_ruler'/>
<h3 class='tour_subheader'>Ask a Question and get clarified</h3>
<div id='ask_question_image' class='right rightalign'>
</div>
<ul class='tour_points'>
    <li>Blah Blah Blah</li>
</ul>    
<br/>
<h3 class='tour_subheader'>Answer a Questin and share support</h3>
<div id='ask_question_image' class='right rightalign'>
</div>
<ul class='tour_points'>
    <li>Blah Blah Blah</li>
</ul>    

templates/tour.html
{%extends 'singlepane_base.html'%}
{% block title %}Tour{% endblock %}
{%block tourtab%}activetab{%endblock%}
{%block content%}
<div id='tour_content'>
    <h1 class="georgia maincontent_header leftalign">Welcome to the Feature Tour</h1>
    <div id='tour_slides'>
        <div id='tour_toc'>
            <ul class='pagination'>
                <li><a href="#">Notepad</a></li>
                <li><a href="#">Achievements</a></li>
                <li><a href="#">Questions &amp; Answers</a></li>
                <li><a href="#">Web-Resume</a></li>
            </ul>
        </div><!-- end of tour_toc -->
        <div class='slides_container'>
            <div>
                {%include 'notepad_tour.html'%}
            </div>
            <div>
                {%include 'achievements_tour.html'%}
            </div>
            <div>
                {%include 'qanda_tour.html'%}
            </div>
            <div>
                {%include 'webresume_tour.html'%}
            </div>
        </div><!--end of slides_container-->
    </div><!-- end of tour_slides -->
</div><!-- end of tour_content -->    
{%endblock%}
{%block extrajs%}
<script type='text/javascript' src="/site_media/js/jquery/plugins/slideshow/slides.min.jquery.js"></script>
<script type="text/javascript">
$(function(){
            $('#tour_slides').slides({
                preloadImage: '/site_media/img/slideshow_pix/loading.gif',
                effect:'slide',
                slideSpeed:500,
                fadeSpeed:500,
                play:0,
                generateNextPrev:true,
                generatePagination:false,
            });
            });
</script>
{%endblock%}
{%block extrastyle%}
<style type='text/css'>
#tour_slides .prev{left:100px;}
.slides_control > div{width:800px;}
</style>
{%endblock%}

templates/webresume_tour.html
<div id='webresume_icon' class='tour_bigicon left'>
</div><!-- end of webresume_icon -->
<h2 class='tour_bigheader centeralign'>Web-Resume <span
        class='orange_underline'>gives you a Multi-Dimensional view of your
        skillset. And not just your projects</span></h2>
<div class='clear'></div>
<hr class='separate_ruler'/>
<h3 class='tour_subheader'>Web-Resume Aggregates all your activity across the
    site</h3>
<div id='webresume_aggregate_image' class='right rightalign'>
</div>
<ul class='tour_points'>
    <li>Blah Blah Blah</li>
</ul>    
<br/>
<h3 class='tour_subheader'>Your two page Word Doc Resume is very outdated.
    Upgrade your career with our Web-Resume</h3>
<div id='webresume_aggregate_image' class='right rightalign'>
</div>
<ul class='tour_points'>
    <li>Blah Blah Blah</li>
</ul>    